# #Cythisiax Edited - HL2 Civil Protection Officer
- type: job
  id: CivilProtectionOfficer
  name: job-name-cpofficer
  description: job-description-cpofficer
  playTimeTracker: JobCivilProtectionOfficer
  startingGear: CPOfficerGear
  icon: "JobIconCivilProtectionOfficer"
  supervisors: job-supervisors-cp
  access:
  - CivilProtection
  - CityExternal
  - Maintenance
  - Cryogenics

- type: startingGear
  id: CPOfficerGear
  equipment:
    head: ClothingHeadHatCpHelmet
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCp
    shoes: ClothingShoesBootsCp
    outerClothing: ClothingOuterVestCp
    mask: ClothingMaskGasCp
    id: SecurityPDA
  storage:
    back:
    - Flash
    - WeaponStunbaton
