# #Misfits Change - HL2-specific departments. All vanilla SS14 departments removed.
# In a Combine-occupied city, only the following departments exist:

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Chef
  - Janitor
  - Musician
  - Reporter
  - ServiceWorker
  - Citizen
  - Refugee
