# #Misfits Change - HL2 Maintenance Worker
- type: job
  id: MaintenanceWorker
  name: job-name-maintenance
  description: job-description-maintenance
  playTimeTracker: JobMaintenanceWorker
  startingGear: MaintenanceGear
  icon: "JobIconMaintenanceWorker"
  supervisors: job-supervisors-logistics
  access:
  - Maintenance
  - Logistics
  - Cryogenics

- type: startingGear
  id: MaintenanceGear
  equipment:
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesLeather
    head: ClothingHeadHatHardhat
    ears: ClothingHeadsetEngineering
    id: EngineerPDA
  storage:
    back:
    - Crowbar
    - Wrench
    - Screwdriver
