# #Misfits Change - HL2 Train Yard Worker
- type: job
  id: TrainYardWorker
  name: job-name-train-yard
  description: job-description-train-yard
  playTimeTracker: JobTrainYardWorker
  startingGear: TrainYardGear
  icon: "JobIconTrainYardWorker"
  supervisors: job-supervisors-logistics
  access:
  - Logistics
  - Maintenance
  - CityExternal
  - Cryogenics

- type: startingGear
  id: TrainYardGear
  equipment:
    shoes: ClothingShoesBootsWork
    gloves: ClothingHandsGlovesLeather
    head: ClothingHeadHatHardhat
    ears: ClothingHeadsetEngineering
    id: ClothingHeadsetEngineering
  storage:
    back:
    - Crowbar
    - Wrench
