# #Misfits Change - HL2 Combine Soldier
- type: job
  id: CombineSoldier
  name: job-name-combine-soldier
  description: job-description-combine-soldier
  playTimeTracker: JobCombineSoldier
  startingGear: CombineSoldierGear
  icon: "JobIconCombineSoldier"
  supervisors: job-supervisors-transhuman
  access:
  - TranshumanArm
  - CityExternal
  - Armory
  - Maintenance
  - Cryogenics

- type: startingGear
  id: CombineSoldierGear
  equipment:
    uniform: ClothingUniformJumpsuitCombine
    head: ClothingHeadHelmetCombine
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCp
    outerClothing: ClothingOuterArmorCombine
    mask: ClothingMaskGasCp
    id: ClothingHeadsetSecurity
  storage:
    back:
    - WeaponPistolMk58
