# #Misfits Change - HL2 Hunter-Seeker Operator
- type: job
  id: HunterSeekerOperator
  name: job-name-hunter-seeker
  description: job-description-hunter-seeker
  playTimeTracker: JobHunterSeekerOperator
  startingGear: HunterSeekerGear
  icon: "JobIconHunterSeeker"
  supervisors: job-supervisors-transhuman
  access:
  - TranshumanArm
  - CityExternal
  - Maintenance
  - Cryogenics

- type: startingGear
  id: HunterSeekerGear
  equipment:
    uniform: ClothingUniformJumpsuitCombine
    head: ClothingHeadHelmetCombine
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCp
    outerClothing: ClothingOuterArmorCombine
    mask: ClothingMaskGasCp
    id: SecurityPDA
